#include "tim2_config.h"



void TIM2_config(void)
{
	GPIO_Init(GPIOC, GPIO_PIN_5, GPIO_MODE_OUT_PP_HIGH_FAST);		//CH1
	GPIO_Init(GPIOD, GPIO_PIN_3, GPIO_MODE_OUT_PP_HIGH_FAST);		//CH2
	GPIO_Init(GPIOA, GPIO_PIN_3, GPIO_MODE_OUT_PP_HIGH_FAST);		//CH3
	
	
	TIM2_DeInit(); 

	CLK_PeripheralClockConfig(CLK_PERIPHERAL_TIMER2, ENABLE);	//16 MHz
	
	TIM2_TimeBaseInit(TIM2_PRESCALER_1, 0xFFFF);					//16 MHz / 65536 = 244 Hz

	TIM2_OC1Init(TIM2_OCMODE_PWM1, TIM2_OUTPUTSTATE_ENABLE, 1, TIM2_OCPOLARITY_HIGH);
	TIM2_OC2Init(TIM2_OCMODE_PWM1, TIM2_OUTPUTSTATE_ENABLE, 1, TIM2_OCPOLARITY_HIGH);
	TIM2_OC3Init(TIM2_OCMODE_PWM1, TIM2_OUTPUTSTATE_ENABLE, 1, TIM2_OCPOLARITY_HIGH);
	TIM2_Cmd(ENABLE);
}